// Regenerates README.md from live GitHub data + IST clock.
// Run by .github/workflows/readme.yml hourly. Node 20+ (global fetch).
// ponytail: hourly cron drifts 10-30min on GitHub; greeting is bucketed coarse
//          (morning/afternoon/evening/night) so drift never shows a wrong phase.

const USER = "Karanjot786";
const FLAGSHIP = ["TermUI", "agent-skills-cli"]; // shown with live stars
const TOKEN = process.env.GITHUB_TOKEN;
const IST_OFFSET_MIN = 5 * 60 + 30;

const gh = (path) =>
  fetch(`https://api.github.com/${path}`, {
    headers: {
      Accept: "application/vnd.github+json",
      ...(TOKEN ? { Authorization: `Bearer ${TOKEN}` } : {}),
    },
  }).then((r) => {
    if (!r.ok) throw new Error(`${path} -> ${r.status}`);
    return r.json();
  });

// --- IST time + greeting ---------------------------------------------------
const ist = new Date(Date.now() + IST_OFFSET_MIN * 60_000);
const h = ist.getUTCHours();
const clock = `${String(h).padStart(2, "0")}:${String(ist.getUTCMinutes()).padStart(2, "0")}`;
const [greet, status] =
  h >= 5 && h < 12 ? ["Good morning", "coffee and changelogs"]
  : h >= 12 && h < 17 ? ["Good afternoon", "deep work, headphones on"]
  : h >= 17 && h < 21 ? ["Good evening", "shipping before dinner"]
  : ["Working late", "best bugs come out at night"];

// --- live data -------------------------------------------------------------
const repos = await gh(`users/${USER}/repos?per_page=100&sort=pushed`);
const mine = repos.filter((r) => !r.fork);
const stars = (name) => mine.find((r) => r.name === name)?.stargazers_count ?? "?";

const latest = mine[0]; // most recently pushed non-fork
const ago = (iso) => {
  const d = Math.floor((Date.now() - new Date(iso)) / 86_400_000);
  return d <= 0 ? "today" : d === 1 ? "1 day ago" : `${d} days ago`;
};

// latest published release of a repo, or null if it has none
const latestRelease = (repo) =>
  gh(`repos/${USER}/${repo}/releases/latest`)
    .then((r) => ({ tag: r.tag_name, at: r.published_at }))
    .catch(() => null);
const shipped = (await Promise.all(FLAGSHIP.map(latestRelease)))
  .map((r, i) => (r ? `${FLAGSHIP[i]} ${r.tag} · ${ago(r.at)}` : null))
  .filter(Boolean)[0]; // newest flagship release we can find

// --- render ----------------------------------------------------------------
const md = `<!-- AUTO-GENERATED by scripts/build-readme.mjs — edit the script, not this file -->
\`\`\`
${greet}. It's ${clock} in Ludhiana (UTC+5:30). ${status[0].toUpperCase() + status.slice(1)}.
\`\`\`

# Karanjot Singh

Solo founder and open-source maintainer. I build dev tools and AI products end to
end: scraping pipelines, search, recommenders, and the frontends on top. Solo, and fast.

GSoC 2024 @ GA4GH · contributor to ELIXIR Cloud & AAI since 2023 · I write
[1MinSummary](https://genzcareer.in), a daily newsletter to 10,000+ readers.

## Building

- [TermUI](https://github.com/${USER}/TermUI) · ${stars("TermUI")}★ · TypeScript framework for terminal apps. Flexbox layout, JSX, hooks, animations, routing, hot reload. 5,018 tests, no curses, no C extensions.
- [agent-skills-cli](https://github.com/${USER}/agent-skills-cli) · ${stars("agent-skills-cli")}★ · one command to install any skill into any AI coding agent. 175K+ skills indexed, 45 agents. All organic.
- [GenZCareer](https://genzcareer.in) · AI job-search platform. Zero to prod in 3 months, multi-provider recommender (Gemini/OpenAI/Azure), 500+ users.
- [CrateGen](https://github.com/${USER}/CrateGen) · GSoC 2024 Python lib converting GA4GH schemas to RO-Crate. FAIR-compliant, 40% faster data exchange.

## Setup

\`\`\`
editor    Cursor + Claude Code
agents    Claude, Copilot, Codex
backend   Node.js, Python
frontend  Next.js, TypeScript, React
data      PostgreSQL (full-text search), Redis, MongoDB
infra     Docker, AWS, GCP, Cloudflare, DigitalOcean
rule      do the hard 20% by hand, hand agents the rest
\`\`\`

I read changelogs. I have opinions on which model is good at what.
Languages: TypeScript, JavaScript, Python, C++, SQL, Bash.

## Live

\`\`\`
${shipped ? `shipped       ${shipped}\n` : ""}last push     ${latest.name} · ${ago(latest.pushed_at)}
generated     ${clock} IST · refreshes hourly via GitHub Actions
\`\`\`

## Play

There's a terminal you can walk around in. No GitHub account, no sign-in —
it's pure markdown, links all the way down. Find the secret room.

    $ ssh guest@karanjot.dev

▶ [**boot the terminal →**](game/start.md)

[GitHub](https://github.com/${USER}) · [LinkedIn](https://linkedin.com/in/karanjot786) · [X](https://x.com/Karanjotdulay) · [Site](https://karanjot.co.in)
`;

await import("node:fs/promises").then((fs) => fs.writeFile("README.md", md));
console.log(`README rebuilt @ ${clock} IST · ${greet} · shipped: ${shipped ?? "n/a"}`);
